version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_OPTS: -no-window -no-audio
      ANDROID_SDK_ROOT2: /opt/android/sdk
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: setup python venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Setup emulator
          command: .circleci/setup_emulator.sh
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd orchestrator/test
            pytest . --cov ../src
      - store_artifacts:
          path: test-reports/
          destination: python_app
