version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: jrusnakli/android:api-28-py3.7
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_OPTS: -no-window -no-audio
      PYTHONASYNCIODEBUG: 1
      ANDROID_SDK_ROOT: /opt/android/sdk
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: setup python venv
          command: |
            /usr/local/bin/python3.7 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install -r requirements.txt
      - run:
          name: Download Dependencies
          command: |
            cd testsupportapps/TestButlerTestApp && ./gradlew androidDependencies
            ./gradlew assembleDebug
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "testsupportapps/TestButlerTestApp/.gradle"
            - "testbutlerservice/.gradle"
      - run:
          name: Setup emulator
          command: |
            yes | ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager "system-images;android-28;default;x86_64"
            echo "DOWNLOADED\n"
            ${ANDROID_SDK_ROOT}/tools/bin/avdmanager create avd -n MTO_emulator -k "system-images;android-28;default;x86_64" -d "pixel_xl" || echo ""
            echo "AVD CREATED\n"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd orchestrator/test
            pytest -s .
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.android/avd/MTO_emulator.avd"
      - store_artifacts:
          path: test-reports/
          destination: python_app
