version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: liwjohnson/android-api-28
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_OPTS: "-no-window -no-audio -no-accel"
      PYTHONASYNCIODEBUG: 1
      CIRCLECI: 1
    steps:
      - checkout
      - restore_cache:
          key: image2-{{ .Branch }}-{{ checksum "checksum.file" }}
      - run:
          name: setup python venv
          command: |
            python3.7 -m venv venv
            . venv/bin/activate
            pip install --upgrade -r requirements.txt
            echo 'export ANDROID_SDK_ROOT="$ANDROID_HOME"' >> $BASH_ENV
            sudo apt-get install libpulse0
      - run:
          name: build androidtestorchestrator
          command: |
            . venv/bin/activate
            pip install -e ./orchestrator
      - save_cache:
          key: image2-{{ .Branch }}-{{ checksum "checksum.file" }}
          paths:
            - "venv"
            - "testsupportapps/.gradle"
            - "testservice/.gradle"
      - run:
          name: Run static analysis
          command: |
            . venv/bin/activate
            cd orchestrator/src
            mypy androidtestorchestrator
            flake8 androidtestorchestrator
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd orchestrator/test
            mkdir -p test-reports/tmp
            /opt/android/sdk/tools/bin/sdkmanager --update
            /opt/android/sdk/tools/bin/sdkmanager emulator
            CIRCLECI=1 ~/code/venv/bin/pytest -s -v -m "not localonly" --html  test-reports/report.html --junitxml=test-reports/all-result.xml --basetemp=test-reports/tmp --cov=../src . --cov-report html:test-reports/coverage
            cat ~/.android/avd/MTO_test_emulator.ini
            cat ~/.android/avd/MTO_test_emulator.avd/config.ini
      - run:
          name: directory
          command: |
            ls /home/circleci/code/testsupportapps/app/build/outputs/apk/androidTest/debug
            ls /home/circleci/code/testsupportapps/app/build/outputs/apk/debug
            find /home/circleci/code/orchestrator/ -name \*.apk
      - store_artifacts:
          path: orchestrator/test/test-reports/
          destination: python_app

      - store_test_results:
          path: orchestrator/test/test-reports/

