version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.7.7
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_OPTS: "-no-window -no-audio -no-accel"
      PYTHONASYNCIODEBUG: 1
      CIRCLECI: 1
    steps:
      - checkout
      - restore_cache:
          key: image2-{{ .Branch }}-{{ checksum "checksum.file" }}
      - run:
          name: setup python venv
          command: |
            python3.7 -m venv venv
            . venv/bin/activate
            pip install --upgrade -r requirements.txt
            sudo apt-get install libpulse0
            yes | sudo apt-get install software-properties-common
            sudo apt-get update
            yes | sudo add-apt-repository ppa:webupd8team/java
            sudo apt-get update
            yes | sudo apt-get install openjdk-8-jdk
            sudo apt-get install git-lfs
            git lfs pull
      - run:
          name: build androidtestorchestrator
          command: |
            . venv/bin/activate
            pip install -e ./orchestrator
      - save_cache:
          key: image2-{{ .Branch }}-{{ checksum "checksum.file" }}
          paths:
            - "venv"
            - "testsupportapps/.gradle"
            - "testservice/.gradle"
      - run:
          name: Run static analysis
          command: |
            . venv/bin/activate
            cd orchestrator/src
            mypy androidtestorchestrator
            flake8 androidtestorchestrator
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd orchestrator/test
            mkdir -p test-reports/tmp
            CIRCLECI=1 ~/code/venv/bin/pytest -s -v -m "not localonly" --html  test-reports/report.html --junitxml=test-reports/all-result.xml --basetemp=test-reports/tmp --cov=../src . --cov-report html:test-reports/coverage
            cat ~/.android/avd/MTO_test_emulator.ini
            cat ~/.android/avd/MTO_test_emulator.avd/config.ini
      - store_artifacts:
          path: orchestrator/test/test-reports/
          destination: python_app

      - store_test_results:
          path: orchestrator/test/test-reports/

